<?php

//Command Constants
define('PACKAGE_LOGIN_CMD', '1001');
define('PACKAGE_OBD_DATA_FLOW_SUPPORTED_CMD', '4004');
define('PACKAGE_DTC_PACKAGE_FOR_PASSENGER_CAR_CMD', '4006');
define('PACKAGE_SNAPSHOOT_FREEZE_FRAME_PACKAGE_CMD', '4005');
define('PACKAGE_GPS_DATA_PACKAGE_CMD', '4001');
define('PACKAGE_OBD_PID_DATA_PACKAGE_CMD', '4002');
define('PACKAGE_ALARMS_DATA_PACKAGE_UPLOAD_CMD', '4007');
define('PACKAGE_GSENSOR_DATA_PACKAGE_CMD', '4003');
define('PACKAGE_SET_REPLY_PACKAGE_CMD', 'A001');
define('PACKAGE_QUERY_RESPONSE_PACKAGE_CMD', 'A002');
define('PACKAGE_HEARTBEAT_PACKAGE_CMD', '1003');
define('PACKAGE_CANCELLATION_PACKAGE_CMD', '1002');

//Package Type Constants
define('PACKAGE_LOGIN', 0);
define('PACKAGE_OBD_DATA_FLOW_SUPPORTED', 1);
define('PACKAGE_DTC_PACKAGE_FOR_PASSENGER_CAR', 2);
define('PACKAGE_SNAPSHOOT_FREEZE_FRAME_PACKAGE', 3);
define('PACKAGE_GPS_DATA_PACKAGE', 4);
define('PACKAGE_OBD_PID_DATA_PACKAGE', 5);
define('PACKAGE_ALARMS_DATA_PACKAGE_UPLOAD', 6);
define('PACKAGE_GSENSOR_DATA_PACKAGE', 7);
define('PACKAGE_SET_REPLY_PACKAGE', 8);
define('PACKAGE_QUERY_RESPONSE_PACKAGE', 9);
define('PACKAGE_HEARTBEAT_PACKAGE', 10);
define('PACKAGE_CANCELLATION_PACKAGE', 11);



?>