    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: wordpress-pv-1
    spec:
      capacity:
        storage: 10Gi
      accessModes:
        – ReadWriteMany
      nfs:
        server: fs-xxxxxxxx.efs.us-west-2.amazonaws.com
        path: “/mysql”
    —
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: wordpress-pv-2
    spec:
      capacity:
        storage: 10Gi
      accessModes:
        – ReadWriteMany
      nfs:
        server: fs-xxxxxxxx.efs.us-west-2.amazonaws.com
        path: “/web”

